        sprintf('%s=%.2g, %.2g; %s=%.2g,%.2g; %s=%.2g,%.2g; %s=%.2g,%.2g',...
            'C_1',max(tensor_C{1}(:)),min(tensor_C{1}(:)),...
            'C_2',max(tensor_C{2}(:)),min(tensor_C{2}(:)),...
            'C_3',max(tensor_C{3}(:)),min(tensor_C{3}(:)),...
            'C_4',max(tensor_C{4}(:)),min(tensor_C{4}(:)))
        sprintf('%s=%.2g, %.2g; %s=%.2g, %.2g; %s=%.2g, %.2g; %s=%.2g, %.2g',...
            'T_1',max(tensor_T{1}(:)),min(tensor_T{1}(:)),...
            'T_2',max(tensor_T{2}(:)),min(tensor_T{2}(:)),...
            'T_3',max(tensor_T{3}(:)),min(tensor_T{3}(:)),...
            'T_4',max(tensor_T{4}(:)),min(tensor_T{4}(:)))
        sprintf('%s=%.2g, %.2g; %s=%.2g, %.2g; %s=%.2g, %.2g; %s=%.2g, %.2g',...
            'T_5',max(tensor_T{5}(:)),min(tensor_T{5}(:)),...
            'T_6',max(tensor_T{6}(:)),min(tensor_T{6}(:)),...
            'T_7',max(tensor_T{7}(:)),min(tensor_T{7}(:)),...
            'T_8',max(tensor_T{8}(:)),min(tensor_T{8}(:)))